name: CD prod server

on:
    push:
        branches:
          - 'main'
        paths:
          - '.github/workflow/CD.yaml'
          - 'trackproject/**'
 
env:
    IMAGE_TAG: ${{ vars.NCR_REGISTRY }}/trackmission:latest


jobs:
    build-push:
        name: build-push
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: set up docker buildx
              uses: docker/setup-buildx-action@v2
            
            - name: Login to NCR
              uses: docker/login-action@v2
              with:
                registry: ${{ vars.NCR_REGISTRY }}
                username: ${{ secrets.NCR_ACCESS_KEY }}
                password: ${{ secrets.NCR_SECRET_KEY }}
  
            - name: bulid and export
              uses: docker/build-push-action@v4
              with:
                  context: trackproject
                  tags: ${{ env.IMAGE_TAG }}
                  push: true
    
    deploy:
        needs: build-push
        name: deploy to staging
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: server access
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.BACKEND_IP }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            script: |
                docker login ${{ vars.NCR_REGISTRY }} \
                -u ${{ secrets.NCR_ACCESS_KEY }} -p ${{ secrets.NCR_SECRET_KEY }}
                docker pull ${{ env.IMAGE_TAG }}
                docker stop trackmission && docker rm trackmission
                docker run -p 8000:8000 -d \
                --env-file /home/lion/.env \
                --name trackmission \
                devops6th-cr.kr.ncr.ntruss.com/trackmission:latest
